import { Knex } from 'knex';
import { v4 as uuidv4 } from 'uuid';
import bcrypt from 'bcryptjs';

const DEMO_USER_ID = '550e8400-e29b-41d4-a716-446655440000';

const DEFAULT_STAGES = [
  { name: 'Wishlist', position: 0 },
  { name: 'Applied', position: 1 },
  { name: 'Recruiter Call', position: 2 },
  { name: 'Technical Screen', position: 3 },
  { name: 'Home Assignment', position: 4 },
  { name: 'Final Interview', position: 5 },
  { name: 'Offer', position: 6 },
  { name: 'Rejected', position: 7 },
  { name: 'Accepted', position: 8 },
];

export async function seed(knex: Knex): Promise<void> {
  // Clean existing data
  await knex('card_activities').del();
  await knex('cards').del();
  await knex('stages').del();
  await knex('refresh_tokens').del();
  await knex('users').del();

  // Create demo user
  const passwordHash = await bcrypt.hash('demo1234', 10);
  await knex('users').insert({
    id: DEMO_USER_ID,
    email: 'demo@jobflow.dev',
    password_hash: passwordHash,
    name: 'Alex Chen',
  });

  // Create stages
  const stageIds: Record<string, string> = {};
  for (const stage of DEFAULT_STAGES) {
    const id = uuidv4();
    stageIds[stage.name] = id;
    await knex('stages').insert({
      id,
      user_id: DEMO_USER_ID,
      name: stage.name,
      position: stage.position,
      is_default: true,
    });
  }

  // Create realistic job application cards
  const cards = [
    {
      id: uuidv4(),
      stage_id: stageIds['Wishlist'],
      position: 0,
      company_name: 'Stripe',
      role_title: 'Senior Full-Stack Engineer',
      application_url: 'https://stripe.com/jobs/listing/senior-full-stack-engineer',
      careers_url: 'https://stripe.com/jobs',
      source: 'Company website',
      location: 'San Francisco, CA',
      work_mode: 'hybrid',
      salary_min: 180000,
      salary_max: 250000,
      priority: 'high',
      notes: 'Great engineering culture. Need to brush up on payment systems knowledge.',
      tech_stack: ['TypeScript', 'React', 'Ruby', 'AWS'],
      tags: ['fintech', 'top-tier', 'growth'],
      interest_level: 5,
      recruiter_name: null,
      recruiter_email: null,
    },
    {
      id: uuidv4(),
      stage_id: stageIds['Wishlist'],
      position: 1,
      company_name: 'Vercel',
      role_title: 'Software Engineer, Platform',
      application_url: 'https://vercel.com/careers',
      careers_url: 'https://vercel.com/careers',
      source: 'Twitter/X',
      location: 'Remote',
      work_mode: 'remote',
      salary_min: 160000,
      salary_max: 220000,
      priority: 'high',
      notes: 'Love their developer tools. Strong Next.js experience is a plus.',
      tech_stack: ['TypeScript', 'Next.js', 'Go', 'Vercel'],
      tags: ['devtools', 'remote-first', 'open-source'],
      interest_level: 5,
    },
    {
      id: uuidv4(),
      stage_id: stageIds['Applied'],
      position: 0,
      company_name: 'Datadog',
      role_title: 'Full-Stack Engineer, Dashboards',
      application_url: 'https://careers.datadoghq.com',
      careers_url: 'https://careers.datadoghq.com',
      source: 'LinkedIn',
      location: 'New York, NY',
      work_mode: 'hybrid',
      salary_min: 170000,
      salary_max: 230000,
      priority: 'medium',
      notes: 'Applied through LinkedIn Easy Apply. Strong observability focus.',
      date_applied: '2026-02-20',
      tech_stack: ['React', 'TypeScript', 'Python', 'Go'],
      tags: ['observability', 'public-company', 'growth'],
      interest_level: 4,
    },
    {
      id: uuidv4(),
      stage_id: stageIds['Applied'],
      position: 1,
      company_name: 'Linear',
      role_title: 'Product Engineer',
      application_url: 'https://linear.app/careers',
      careers_url: 'https://linear.app/careers',
      source: 'Referral - Sarah Kim',
      location: 'Remote',
      work_mode: 'remote',
      salary_min: 150000,
      salary_max: 200000,
      priority: 'high',
      notes: 'Got a warm referral from Sarah. Love their product philosophy.',
      date_applied: '2026-02-25',
      last_interaction_date: '2026-02-25',
      next_followup_date: '2026-03-11',
      tech_stack: ['TypeScript', 'React', 'Node.js', 'PostgreSQL'],
      tags: ['devtools', 'startup', 'product-led'],
      interest_level: 5,
      recruiter_name: 'Maya Johnson',
      recruiter_email: 'maya@linear.app',
    },
    {
      id: uuidv4(),
      stage_id: stageIds['Recruiter Call'],
      position: 0,
      company_name: 'Figma',
      role_title: 'Senior Software Engineer, Editor',
      application_url: 'https://www.figma.com/careers',
      careers_url: 'https://www.figma.com/careers',
      source: 'Recruiter outreach',
      location: 'San Francisco, CA',
      work_mode: 'hybrid',
      salary_min: 190000,
      salary_max: 260000,
      priority: 'critical',
      notes: 'Recruiter reached out on LinkedIn. Call scheduled for next week. Need to prepare questions about the editor team.',
      date_applied: '2026-02-15',
      last_interaction_date: '2026-03-01',
      next_followup_date: '2026-03-10',
      tech_stack: ['TypeScript', 'C++', 'WebAssembly', 'React'],
      tags: ['design-tools', 'top-tier', 'challenging'],
      interest_level: 5,
      recruiter_name: 'James Liu',
      recruiter_email: 'james.liu@figma.com',
    },
    {
      id: uuidv4(),
      stage_id: stageIds['Recruiter Call'],
      position: 1,
      company_name: 'Notion',
      role_title: 'Software Engineer, Backend',
      application_url: 'https://www.notion.so/careers',
      careers_url: 'https://www.notion.so/careers',
      source: 'LinkedIn',
      location: 'New York, NY',
      work_mode: 'hybrid',
      salary_min: 170000,
      salary_max: 240000,
      priority: 'medium',
      notes: 'Had initial chat with recruiter. They want someone strong in distributed systems.',
      date_applied: '2026-02-10',
      last_interaction_date: '2026-02-28',
      next_followup_date: '2026-03-07',
      tech_stack: ['Kotlin', 'TypeScript', 'PostgreSQL', 'Redis'],
      tags: ['productivity', 'scale', 'growth'],
      interest_level: 4,
      recruiter_name: 'Priya Sharma',
      recruiter_email: 'priya@makenotion.com',
    },
    {
      id: uuidv4(),
      stage_id: stageIds['Technical Screen'],
      position: 0,
      company_name: 'Shopify',
      role_title: 'Senior Developer, Checkout',
      application_url: 'https://www.shopify.com/careers',
      careers_url: 'https://www.shopify.com/careers',
      source: 'Company website',
      location: 'Remote (US/Canada)',
      work_mode: 'remote',
      salary_min: 165000,
      salary_max: 225000,
      priority: 'high',
      notes: 'Technical screen scheduled for Thursday. Focus on system design and React patterns. Checkout team is interesting.',
      date_applied: '2026-02-05',
      last_interaction_date: '2026-03-03',
      next_followup_date: '2026-03-08',
      tech_stack: ['React', 'TypeScript', 'Ruby on Rails', 'GraphQL'],
      tags: ['e-commerce', 'remote-first', 'public-company'],
      interest_level: 4,
      recruiter_name: 'Tom Richards',
      recruiter_email: 'tom.richards@shopify.com',
    },
    {
      id: uuidv4(),
      stage_id: stageIds['Home Assignment'],
      position: 0,
      company_name: 'Supabase',
      role_title: 'Full-Stack Engineer',
      application_url: 'https://supabase.com/careers',
      careers_url: 'https://supabase.com/careers',
      source: 'Twitter/X',
      location: 'Remote',
      work_mode: 'remote',
      salary_min: 150000,
      salary_max: 200000,
      priority: 'high',
      notes: 'Take-home: Build a real-time dashboard component. Due in 5 days. Using their own platform which is cool.',
      date_applied: '2026-01-28',
      last_interaction_date: '2026-03-02',
      next_followup_date: '2026-03-09',
      tech_stack: ['TypeScript', 'Next.js', 'PostgreSQL', 'Elixir'],
      tags: ['open-source', 'startup', 'devtools'],
      interest_level: 5,
      recruiter_name: 'Anya Petrova',
      recruiter_email: 'anya@supabase.io',
    },
    {
      id: uuidv4(),
      stage_id: stageIds['Final Interview'],
      position: 0,
      company_name: 'Tailwind Labs',
      role_title: 'UI Engineer',
      application_url: 'https://tailwindcss.com/careers',
      careers_url: 'https://tailwindcss.com/careers',
      source: 'Direct application',
      location: 'Remote',
      work_mode: 'remote',
      salary_min: 160000,
      salary_max: 210000,
      priority: 'critical',
      notes: 'Final round panel interview next Tuesday. 4 sessions: system design, pair coding, product sense, team fit. Need to prepare Tailwind CSS internals knowledge.',
      date_applied: '2026-01-20',
      last_interaction_date: '2026-03-04',
      next_followup_date: '2026-03-11',
      tech_stack: ['TypeScript', 'React', 'Rust', 'CSS'],
      tags: ['open-source', 'small-team', 'design-systems'],
      interest_level: 5,
      recruiter_name: 'Robin Malfait',
      recruiter_email: 'robin@tailwindlabs.com',
    },
    {
      id: uuidv4(),
      stage_id: stageIds['Offer'],
      position: 0,
      company_name: 'PlanetScale',
      role_title: 'Senior Software Engineer',
      application_url: 'https://planetscale.com/careers',
      careers_url: 'https://planetscale.com/careers',
      source: 'Referral - Mike Torres',
      location: 'Remote',
      work_mode: 'remote',
      salary_min: 175000,
      salary_max: 230000,
      priority: 'critical',
      notes: 'Received offer! Base: $195K, RSUs: $80K/4yr, signing bonus: $15K. Need to respond by March 15. Great team, interesting database infra work.',
      date_applied: '2026-01-10',
      last_interaction_date: '2026-03-05',
      next_followup_date: '2026-03-15',
      tech_stack: ['Go', 'MySQL', 'Vitess', 'Kubernetes'],
      tags: ['databases', 'infrastructure', 'remote-first'],
      interest_level: 4,
      recruiter_name: 'Diana Chen',
      recruiter_email: 'diana.chen@planetscale.com',
    },
    {
      id: uuidv4(),
      stage_id: stageIds['Rejected'],
      position: 0,
      company_name: 'Netflix',
      role_title: 'Senior UI Engineer',
      application_url: 'https://jobs.netflix.com',
      careers_url: 'https://jobs.netflix.com',
      source: 'LinkedIn',
      location: 'Los Gatos, CA',
      work_mode: 'onsite',
      salary_min: 250000,
      salary_max: 400000,
      priority: 'low',
      notes: 'Rejected after technical screen. Feedback: needed more experience with large-scale video streaming infrastructure. Good learning experience.',
      date_applied: '2026-01-15',
      last_interaction_date: '2026-02-20',
      tech_stack: ['React', 'Java', 'Node.js', 'AWS'],
      tags: ['streaming', 'faang', 'high-comp'],
      interest_level: 4,
    },
    {
      id: uuidv4(),
      stage_id: stageIds['Rejected'],
      position: 1,
      company_name: 'Airbnb',
      role_title: 'Staff Engineer, Payments',
      application_url: 'https://careers.airbnb.com',
      careers_url: 'https://careers.airbnb.com',
      source: 'Company website',
      location: 'San Francisco, CA',
      work_mode: 'hybrid',
      salary_min: 220000,
      salary_max: 350000,
      priority: 'low',
      notes: 'Didn\'t pass the system design round. The payments domain was very specific. Might reapply in 6 months with more fintech experience.',
      date_applied: '2026-01-05',
      last_interaction_date: '2026-02-15',
      tech_stack: ['Java', 'Kotlin', 'React', 'GraphQL'],
      tags: ['travel', 'public-company', 'payments'],
      interest_level: 3,
    },
    {
      id: uuidv4(),
      stage_id: stageIds['Applied'],
      position: 2,
      company_name: 'Raycast',
      role_title: 'Software Engineer, Extensions',
      application_url: 'https://www.raycast.com/careers',
      careers_url: 'https://www.raycast.com/careers',
      source: 'Product Hunt',
      location: 'Remote (EU timezone preferred)',
      work_mode: 'remote',
      salary_min: 140000,
      salary_max: 190000,
      priority: 'medium',
      notes: 'Love using Raycast daily. Applied to extensions team. Haven\'t heard back yet.',
      date_applied: '2026-03-01',
      last_interaction_date: '2026-03-01',
      next_followup_date: '2026-03-15',
      tech_stack: ['TypeScript', 'React', 'Swift', 'Node.js'],
      tags: ['devtools', 'startup', 'mac-native'],
      interest_level: 4,
    },
    {
      id: uuidv4(),
      stage_id: stageIds['Accepted'],
      position: 0,
      company_name: 'Deno',
      role_title: 'Runtime Engineer',
      application_url: 'https://deno.com/jobs',
      careers_url: 'https://deno.com/jobs',
      source: 'Conference meetup',
      location: 'Remote',
      work_mode: 'remote',
      salary_min: 155000,
      salary_max: 200000,
      priority: 'critical',
      notes: 'Accepted this offer 2 months ago! Start date: April 1. Working on the Deno runtime core. Super excited about Rust + TypeScript combo.',
      date_applied: '2025-12-01',
      last_interaction_date: '2026-01-15',
      tech_stack: ['Rust', 'TypeScript', 'V8', 'Tokio'],
      tags: ['open-source', 'runtime', 'startup'],
      interest_level: 5,
      recruiter_name: 'Luca Casonato',
      recruiter_email: 'luca@deno.com',
    },
    {
      id: uuidv4(),
      stage_id: stageIds['Wishlist'],
      position: 2,
      company_name: 'Cloudflare',
      role_title: 'Systems Engineer, Workers',
      application_url: 'https://www.cloudflare.com/careers',
      careers_url: 'https://www.cloudflare.com/careers',
      source: 'Blog post',
      location: 'Austin, TX',
      work_mode: 'hybrid',
      salary_min: 170000,
      salary_max: 230000,
      priority: 'medium',
      notes: 'Read their blog about Workers runtime. Fascinating edge computing work. Need to research the team more.',
      tech_stack: ['Rust', 'C++', 'JavaScript', 'Lua'],
      tags: ['infrastructure', 'edge-computing', 'public-company'],
      interest_level: 4,
    },
  ];

  for (const card of cards) {
    await knex('cards').insert({
      ...card,
      user_id: DEMO_USER_ID,
      tech_stack: card.tech_stack ? `{${card.tech_stack.map(t => `"${t}"`).join(',')}}` : '{}',
      tags: card.tags ? `{${card.tags.map(t => `"${t}"`).join(',')}}` : '{}',
    });
  }

  // Add some activity history for a few cards
  const figmaCard = cards.find(c => c.company_name === 'Figma')!;
  const activities = [
    {
      card_id: figmaCard.id,
      user_id: DEMO_USER_ID,
      action: 'created',
      note: 'Added Figma opportunity from recruiter outreach',
      created_at: '2026-02-15T10:00:00Z',
    },
    {
      card_id: figmaCard.id,
      user_id: DEMO_USER_ID,
      action: 'moved',
      field_changed: 'stage',
      old_value: 'Applied',
      new_value: 'Recruiter Call',
      note: 'Recruiter James Liu reached out to schedule a call',
      created_at: '2026-02-28T14:30:00Z',
    },
    {
      card_id: figmaCard.id,
      user_id: DEMO_USER_ID,
      action: 'note_added',
      note: 'Great call with James. Team is working on next-gen editor features. They use C++ compiled to WASM.',
      created_at: '2026-03-01T16:00:00Z',
    },
  ];

  for (const activity of activities) {
    await knex('card_activities').insert({ id: uuidv4(), ...activity });
  }
}
